### ISSUE TITLE
Looking for some context on this repository

### ISSUE THREAD

**Issue by Khronoswebmaster** [h-s-c/libKD#14]
James from Khronos here. We are looking for some context and background on your repository. As OpenKODE is not currently an active standard, we'd love to know more about your thoughts on developing this. Would you be able to reach out to me (webmaster at khronos). Thank you.

**Comment by h-s-c** [comment]
This is an personal exercise in implementing a library from a specification and maintaining it. OpenKODE was chosen because it didn't have a finished open source implementation and had stuff in it i found interesting. I don't think its sensible to invest into developing the OpenKODE standard further. There are already a bunch of good open source "multimedia" and game porting libraries (SDL etc.) available to developers.
